# Generated by Django 6.0.1 on 2026-02-22 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('architecture', 'Architectural Decision'), ('backend', 'Backend Design reasoning'), ('performance', 'Performance Optimization'), ('cicd', 'CI/CD Strategy'), ('tradeoffs', 'Technology Tradeoffs'), ('other', 'Other')], default='architecture', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('summary', models.TextField(help_text='Short abstract of the note')),
                ('content', models.TextField(help_text='Detailed analytical content (Markdown)')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_overview',
            field=models.TextField(blank=True, help_text='High-level architecture description'),
        ),
        migrations.AddField(
            model_name='project',
            name='constraints',
            field=models.TextField(blank=True, help_text='Technical or business constraints'),
        ),
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.TextField(blank=True, help_text='Background context of the project'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='engineering_decisions',
            field=models.TextField(blank=True, help_text='Key technical choices and why they were made'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons',
            field=models.TextField(blank=True, help_text='What was learned during implementation'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='performance_security',
            field=models.TextField(blank=True, help_text='Performance optimizations and security measures'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, help_text='The core problem the project solves'),
        ),
        migrations.AddField(
            model_name='project',
            name='tradeoffs',
            field=models.TextField(blank=True, help_text='What was sacrificed/compromised and why'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Short summary for preview'),
        ),
    ]
