# Generated by Django 6.0.1 on 2026-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_engineeringnote_delete_blogpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('content', models.TextField(help_text='Markdown content')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
        ),
        migrations.DeleteModel(
            name='EngineeringNote',
        ),
        migrations.RemoveField(
            model_name='project',
            name='architecture_overview',
        ),
        migrations.RemoveField(
            model_name='project',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='project',
            name='context',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='engineering_decisions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='performance_security',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tradeoffs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='philosophy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
