# Generated by Django 6.0.1 on 2026-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Visitor Counts',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='clicks',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this project was clicked'),
        ),
    ]
