# Generated by Django 6.0.1 on 2026-03-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visitorcount_project_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed markdown content for the Case Study page'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Short abstract for the project card'),
        ),
    ]
