# Generated by Django 6.0.1 on 2026-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_content_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Analytics',
            },
        ),
    ]
