# Generated by Django 6.0.1 on 2026-03-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_portfolioanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('last_commit', models.DateTimeField(blank=True, null=True)),
                ('repo_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
                'ordering': ['-stars'],
            },
        ),
    ]
