# Generated by Django 6.0.1 on 2026-03-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_githubrepo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('architecture', models.TextField(help_text='Detailed architecture description (Markdown supported)')),
                ('tech_stack', models.TextField(help_text='Comma-separated tech stack or JSON formatted string')),
                ('challenges', models.TextField()),
                ('performance_improvements', models.TextField(blank=True, null=True)),
                ('lessons_learned', models.TextField()),
                ('github_repo_url', models.URLField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Case Study',
                'verbose_name_plural': 'Project Case Studies',
                'ordering': ['-created_at'],
            },
        ),
    ]
