# Generated by Django 6.0 on 2026-03-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectcasestudy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['order', '-date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
