# Generated by Django 6.0.1 on 2026-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_blogpost_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
