name: Keep Backend Alive

on:
  schedule:
    - cron: "*/8 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print Time
        run: date

      - name: Ping Backend
        run: curl -I https://fullstack-portfolio-vdvq.onrender.com/health/